# syntax=docker/dockerfile:1.10.0
FROM ruby:3.2-alpine

RUN addgroup -g 9999 -S buildkite-agent \
 && adduser -D -G buildkite-agent -S -u 9999 buildkite-agent

ENV APP_HOME /var/www
WORKDIR $APP_HOME

RUN bundle config --local app_config /usr/local/bundle/config \
 && bundle config --local path vendor/bundle \
 && bundle config --local "mirror.https://rubygems.org" "https://dl.cloudsmith.io/basic/gusto/gusto/ruby/" \
 && mkdir /home/buildkite-agent/.gem

COPY Gemfile* rubocop-gusto.gemspec $APP_HOME/
COPY lib/rubocop/gusto/version.rb $APP_HOME/lib/rubocop/gusto/version.rb

RUN --mount=type=secret,id=cloudsmith_api_key,env=CLOUDSMITH_API_KEY \
    apk add --no-cache build-base \
 && BUNDLE_DL__CLOUDSMITH__IO="token:${CLOUDSMITH_API_KEY}" bundle install \
 && apk del build-base

COPY . $APP_HOME

RUN chown -R buildkite-agent:buildkite-agent \
      $APP_HOME \
      /home/buildkite-agent \
      /usr/local/bundle/config

USER buildkite-agent
