name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 3.2
          - 3.3
          - 3.4
    name: "Tests: Ruby ${{ matrix.ruby }}"
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Test
        run: bundle exec rspec
  lint:
    runs-on: ubuntu-latest
    name: "Linter"
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Set up Ruby
        uses: ruby/setup-ruby@3ff19f5e2baf30647122352b96108b1fbe250c64 # v1.299.0
        with:
          bundler-cache: true
          ruby-version: 3.4
      - name: Run linter
        run: bundle exec rubocop
