name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on:
      group: gusto-ubuntu-default
    strategy:
      matrix:
        ruby:
          - 3.2
          - 3.3
          - 3.4
    name: "Tests: Ruby ${{ matrix.ruby }}"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}
      - name: Test
        run: bundle exec rspec
  lint:
    runs-on:
      group: gusto-ubuntu-default
    name: "Linter"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.4
      - name: Run linter
        run: bundle exec rubocop
