name: Release Gem

on:
  release:
    types: [published]

jobs:
  release:
    if: github.repository == 'gusto/rubocop-gusto'
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # v1.321.0
        with:
          bundler-cache: false
          ruby-version: ruby
      - name: Install gems
        run: bundle install --jobs 4

      # Release
      - uses: rubygems/release-gem@7f9650160c1a4e7989fdc9855807bdbd421d8b6b # v1.4.1

      - name: Upload gem to release
        continue-on-error: true  # May fail due to IP allow list restrictions
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ github.event.release.tag_name }}
        run: gh release upload "$RELEASE_TAG" pkg/rubocop-gusto-*.gem
